title: Bioinspired Communication & Ethics
description: Graduate course on bioinspired systems, communication, and ethics

theme: minima

url: "https://tengzhang48.github.io"
baseurl: "/Bioinspired-Communication-Ethics"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: page
