# Site settings
title: "MAE 600: Bioinspired Communication & Ethics"
email: tzhang48@syr.edu
description: >-
  Graduate course on bioinspired communication and ethics at Syracuse University
baseurl: "/Bioinspired-Communication-Ethics"
url: "https://tengzhang48.github.io"
repository: "tengzhang48/Bioinspired-Communication-Ethics"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Collection configuration
collections:
  modules:
    output: true
    permalink: /modules/:path/
