# _config.yml
title: Bioinspired Communication & Ethics
---
layout: home
# Remove title here to prevent duplication
---

# Welcome to the Course! <!-- Keep only this heading -->
Course description text goes here...

plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - index.md      # Welcome page
  - foundation.md    # Team work
  - science.md       # Scientific Literature Review
  - proposal.md      # Proposal Writing and Review
  - ethics.md     # Research Ethics
# Minimal safe configuration
