title: Bioinspired Communication & Ethics
description: Graduate course on bioinspired systems, communication, and ethics
theme: minima
url: "https://tengzhang48.github.io/Bioinspired-Communication-Ethics/" 

# Navigation configuration
header_pages:
  - index.md       # First in navigation
  - foundation.md    # Team work
  - science.md       # Scientific Literature Review
  - proposal.md      # Proposal Writing and Review
  - ethics.md      # Second in navigation

# Default page settings
defaults:
  - scope:
      path: ""
    values:
      layout: page

# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
